openapi: 3.2.0
info:
  version: '2020-05-15'
  x-release: v4
  title: 'AWS App Runner #X Amz Target=AppRunner.DeleteVpcIngressConne…'
  description: 'App Runner

    App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS App Runner #X Amz Target=AppRunner.DeleteVpcIngressConne…'
paths:
  /#X-Amz-Target=AppRunner.DeleteVpcIngressConnection:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteVpcIngressConnection
      description: 'Delete an App Runner VPC Ingress Connection resource that''s associated with an App Runner service. The VPC Ingress Connection must be in one of the following states to be deleted:


        AVAILABLE


        FAILED_CREATION


        FAILED_UPDATE


        FAILED_DELETION'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteVpcIngressConnectionResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '483':
          description: InvalidStateException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidStateException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteVpcIngressConnectionRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.DeleteVpcIngressConnection
      tags:
      - 'AWS App Runner #X Amz Target=AppRunner.DeleteVpcIngressConne…'
      summary: Delete vpc ingress connection
      x-summary-source: derived
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    VpcIngressConnectionStatus:
      type: string
      enum:
      - AVAILABLE
      - PENDING_CREATION
      - PENDING_UPDATE
      - PENDING_DELETION
      - FAILED_CREATION
      - FAILED_UPDATE
      - FAILED_DELETION
      - DELETED
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 51200
    DomainName:
      type: string
      pattern: '[A-Za-z0-9*.-]{1,255}'
      minLength: 1
      maxLength: 255
    DeleteVpcIngressConnectionRequest:
      type: object
      required:
      - VpcIngressConnectionArn
      title: DeleteVpcIngressConnectionRequest
      properties:
        VpcIngressConnectionArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of the App Runner VPC Ingress Connection that you want to delete.
    DeleteVpcIngressConnectionResponse:
      type: object
      required:
      - VpcIngressConnection
      properties:
        VpcIngressConnection:
          allOf:
          - $ref: '#/components/schemas/VpcIngressConnection'
          - description: A description of the App Runner VPC Ingress Connection that this request just deleted.
    VpcIngressConnection:
      type: object
      properties:
        VpcIngressConnectionArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: 'The Amazon Resource Name (ARN) of the VPC Ingress Connection. '
        VpcIngressConnectionName:
          allOf:
          - $ref: '#/components/schemas/VpcIngressConnectionName'
          - description: The customer-provided VPC Ingress Connection name.
        ServiceArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: 'The Amazon Resource Name (ARN) of the service associated with the VPC Ingress Connection. '
        Status:
          allOf:
          - $ref: '#/components/schemas/VpcIngressConnectionStatus'
          - description: 'The current status of the VPC Ingress Connection. The VPC Ingress Connection displays one of the following statuses: <code>AVAILABLE</code>, <code>PENDING_CREATION</code>, <code>PENDING_UPDATE</code>, <code>PENDING_DELETION</code>,<code>FAILED_CREATION</code>, <code>FAILED_UPDATE</code>, <code>FAILED_DELETION</code>, and <code>DELETED</code>.. '
        AccountId:
          allOf:
          - $ref: '#/components/schemas/CustomerAccountId'
          - description: The Account Id you use to create the VPC Ingress Connection resource.
        DomainName:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: The domain name associated with the VPC Ingress Connection resource.
        IngressVpcConfiguration:
          allOf:
          - $ref: '#/components/schemas/IngressVpcConfiguration'
          - description: Specifications for the customer’s VPC and related PrivateLink VPC endpoint that are used to associate with the VPC Ingress Connection resource.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: '<p>The time when the VPC Ingress Connection was created. It''s in the Unix time stamp format.</p> <ul> <li> <p> Type: Timestamp </p> </li> <li> <p> Required: Yes </p> </li> </ul>'
        DeletedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: '<p>The time when the App Runner service was deleted. It''s in the Unix time stamp format.</p> <ul> <li> <p> Type: Timestamp </p> </li> <li> <p> Required: No </p> </li> </ul>'
      description: The App Runner resource that specifies an App Runner endpoint for incoming traffic. It establishes a connection between a VPC interface endpoint and a App Runner service, to make your App Runner service accessible from only within an Amazon VPC.
    ResourceNotFoundException: {}
    InternalServiceErrorException: {}
    Timestamp:
      type: string
      format: date-time
    VpcIngressConnectionName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9\-_]{3,39}'
      minLength: 4
      maxLength: 40
    CustomerAccountId:
      type: string
      pattern: '[0-9]{12}'
      minLength: 12
      maxLength: 12
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    InvalidStateException: {}
    InvalidRequestException: {}
    IngressVpcConfiguration:
      type: object
      properties:
        VpcId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The ID of the VPC that is used for the VPC endpoint.
        VpcEndpointId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The ID of the VPC endpoint that your App Runner service connects to. '
      description: The configuration of your VPC and the associated VPC endpoint. The VPC endpoint is an Amazon Web Services PrivateLink resource that allows access to your App Runner services from within an Amazon VPC.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
