openapi: 3.2.0
info:
  version: '2020-05-15'
  x-release: v4
  title: 'AWS App Runner #X Amz Target=AppRunner.DescribeVpcConnector……'
  description: 'App Runner

    App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS App Runner #X Amz Target=AppRunner.DescribeVpcConnector…'
paths:
  /#X-Amz-Target=AppRunner.DescribeVpcConnector:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeVpcConnector
      description: Return a description of an App Runner VPC connector resource.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeVpcConnectorResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeVpcConnectorRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.DescribeVpcConnector
      tags:
      - 'AWS App Runner #X Amz Target=AppRunner.DescribeVpcConnector…'
      summary: Describe vpc connector
      x-summary-source: derived
components:
  schemas:
    Integer:
      type: integer
    VpcConnectorName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9\-_]{3,39}'
      minLength: 4
      maxLength: 40
    VpcConnector:
      type: object
      properties:
        VpcConnectorName:
          allOf:
          - $ref: '#/components/schemas/VpcConnectorName'
          - description: The customer-provided VPC connector name.
        VpcConnectorArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of this VPC connector.
        VpcConnectorRevision:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: '<p>The revision of this VPC connector. It''s unique among all the active connectors (<code>"Status": "ACTIVE"</code>) that share the same <code>Name</code>.</p> <note> <p>At this time, App Runner supports only one revision per name.</p> </note>'
        Subnets:
          allOf:
          - $ref: '#/components/schemas/StringList'
          - description: A list of IDs of subnets that App Runner uses for your service. All IDs are of subnets of a single Amazon VPC.
        SecurityGroups:
          allOf:
          - $ref: '#/components/schemas/StringList'
          - description: A list of IDs of security groups that App Runner uses for access to Amazon Web Services resources under the specified subnets. If not specified, App Runner uses the default security group of the Amazon VPC. The default security group allows all outbound traffic.
        Status:
          allOf:
          - $ref: '#/components/schemas/VpcConnectorStatus'
          - description: The current state of the VPC connector. If the status of a connector revision is <code>INACTIVE</code>, it was deleted and can't be used. Inactive connector revisions are permanently removed some time after they are deleted.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the VPC connector was created. It's in Unix time stamp format.
        DeletedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the VPC connector was deleted. It's in Unix time stamp format.
      description: <p>Describes an App Runner VPC connector resource. A VPC connector describes the Amazon Virtual Private Cloud (Amazon VPC) that an App Runner service is associated with, and the subnets and security group that are used.</p> <p>Multiple revisions of a connector might have the same <code>Name</code> and different <code>Revision</code> values.</p> <note> <p>At this time, App Runner supports only one revision per name.</p> </note>
    DescribeVpcConnectorResponse:
      type: object
      required:
      - VpcConnector
      properties:
        VpcConnector:
          allOf:
          - $ref: '#/components/schemas/VpcConnector'
          - description: A description of the App Runner VPC connector that you specified in this request.
    VpcConnectorStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 51200
    ResourceNotFoundException: {}
    InternalServiceErrorException: {}
    Timestamp:
      type: string
      format: date-time
    DescribeVpcConnectorRequest:
      type: object
      required:
      - VpcConnectorArn
      title: DescribeVpcConnectorRequest
      properties:
        VpcConnectorArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: <p>The Amazon Resource Name (ARN) of the App Runner VPC connector that you want a description for.</p> <p>The ARN must be a full VPC connector ARN.</p>
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    InvalidRequestException: {}
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
