openapi: 3.2.0
info:
  version: '2020-05-15'
  x-release: v4
  title: 'AWS App Runner #X Amz Target=AppRunner.ListVpcIngressConnect…'
  description: 'App Runner

    App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS App Runner #X Amz Target=AppRunner.ListVpcIngressConnect…'
paths:
  /#X-Amz-Target=AppRunner.ListVpcIngressConnections:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListVpcIngressConnections
      description: Return a list of App Runner VPC Ingress Connections in your Amazon Web Services account.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListVpcIngressConnectionsResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListVpcIngressConnectionsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.ListVpcIngressConnections
      tags:
      - 'AWS App Runner #X Amz Target=AppRunner.ListVpcIngressConnect…'
      summary: List vpc ingress connections
      x-summary-source: derived
components:
  schemas:
    ListVpcIngressConnectionsRequest:
      type: object
      title: ListVpcIngressConnectionsRequest
      properties:
        Filter:
          allOf:
          - $ref: '#/components/schemas/ListVpcIngressConnectionsFilter'
          - description: The VPC Ingress Connections to be listed based on either the Service Arn or Vpc Endpoint Id, or both.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResults'
          - description: <p>The maximum number of results to include in each response (result page). It's used for a paginated request.</p> <p>If you don't specify <code>MaxResults</code>, the request retrieves all available results in a single response.</p>
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: <p>A token from a previous result page. It's used for a paginated request. The request retrieves the next result page. All other parameter values must be identical to the ones that are specified in the initial request.</p> <p>If you don't specify <code>NextToken</code>, the request retrieves the first result page.</p>
    NextToken:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    VpcIngressConnectionSummary:
      type: object
      properties:
        VpcIngressConnectionArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: 'The Amazon Resource Name (ARN) of the VPC Ingress Connection. '
        ServiceArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: 'The Amazon Resource Name (ARN) of the service associated with the VPC Ingress Connection. '
      description: Provides summary information about an VPC Ingress Connection, which includes its VPC Ingress Connection ARN and its associated Service ARN.
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    ListVpcIngressConnectionsFilter:
      type: object
      properties:
        ServiceArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: 'The Amazon Resource Name (ARN) of a service to filter by. '
        VpcEndpointId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The ID of a VPC Endpoint to filter by. '
      description: Returns a list of VPC Ingress Connections based on the filter provided. It can return either <code>ServiceArn</code> or <code>VpcEndpointId</code>, or both.
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 51200
    ListVpcIngressConnectionsResponse:
      type: object
      required:
      - VpcIngressConnectionSummaryList
      properties:
        VpcIngressConnectionSummaryList:
          allOf:
          - $ref: '#/components/schemas/VpcIngressConnectionSummaryList'
          - description: A list of summary information records for VPC Ingress Connections. In a paginated request, the request returns up to <code>MaxResults</code> records for each call.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token that you can pass in a subsequent request to get the next result page. It's returned in a paginated request.
    InternalServiceErrorException: {}
    InvalidRequestException: {}
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    VpcIngressConnectionSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/VpcIngressConnectionSummary'
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
