# x-archived-from: amazon-app-runner-x-amz-target-apprunner-deleteobservabilityconfiguration-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2020-05-15'
  x-release: v4
  title: 'AWS App Runner #X Amz Target=AppRunner.DeleteObservabilityCo…'
  description: 'App Runner

    App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AppRunner.DeleteObservabilityConfiguration'
paths:
  /#X-Amz-Target=AppRunner.DeleteObservabilityConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteObservabilityConfiguration
      description: Delete an App Runner observability configuration resource. You can delete a specific revision or the latest active revision. You can't delete a configuration that's used by one or more App Runner services.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteObservabilityConfigurationResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteObservabilityConfigurationRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.DeleteObservabilityConfiguration
      tags:
      - '#X Amz Target=AppRunner.DeleteObservabilityConfiguration'
      summary: Delete observability configuration
      x-summary-source: derived
components:
  schemas:
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    Boolean:
      type: boolean
    TraceConfiguration:
      type: object
      required:
      - Vendor
      properties:
        Vendor:
          allOf:
          - $ref: '#/components/schemas/TracingVendor'
          - description: The implementation provider chosen for tracing App Runner services.
      description: Describes the configuration of the tracing feature within an App Runner observability configuration.
    ObservabilityConfigurationName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9\-_]{3,31}'
      minLength: 4
      maxLength: 32
    TracingVendor:
      type: string
      enum:
      - AWSXRAY
    DeleteObservabilityConfigurationRequest:
      type: object
      required:
      - ObservabilityConfigurationArn
      title: DeleteObservabilityConfigurationRequest
      properties:
        ObservabilityConfigurationArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: <p>The Amazon Resource Name (ARN) of the App Runner observability configuration that you want to delete.</p> <p>The ARN can be a full observability configuration ARN, or a partial ARN ending with either <code>.../<i>name</i> </code> or <code>.../<i>name</i>/<i>revision</i> </code>. If a revision isn't specified, the latest active revision is deleted.</p>
    Integer:
      type: integer
    ResourceNotFoundException: {}
    Timestamp:
      type: string
      format: date-time
    InternalServiceErrorException: {}
    InvalidRequestException: {}
    ObservabilityConfiguration:
      type: object
      properties:
        ObservabilityConfigurationArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of this observability configuration.
        ObservabilityConfigurationName:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfigurationName'
          - description: The customer-provided observability configuration name. It can be used in multiple revisions of a configuration.
        TraceConfiguration:
          allOf:
          - $ref: '#/components/schemas/TraceConfiguration'
          - description: The configuration of the tracing feature within this observability configuration. If not specified, tracing isn't enabled.
        ObservabilityConfigurationRevision:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: 'The revision of this observability configuration. It''s unique among all the active configurations (<code>"Status": "ACTIVE"</code>) that share the same <code>ObservabilityConfigurationName</code>.'
        Latest:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: It's set to <code>true</code> for the configuration with the highest <code>Revision</code> among all configurations that share the same <code>ObservabilityConfigurationName</code>. It's set to <code>false</code> otherwise.
        Status:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfigurationStatus'
          - description: The current state of the observability configuration. If the status of a configuration revision is <code>INACTIVE</code>, it was deleted and can't be used. Inactive configuration revisions are permanently removed some time after they are deleted.
        CreatedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the observability configuration was created. It's in Unix time stamp format.
        DeletedAt:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time when the observability configuration was deleted. It's in Unix time stamp format.
      description: <p>Describes an App Runner observability configuration resource. Multiple revisions of a configuration have the same <code>ObservabilityConfigurationName</code> and different <code>ObservabilityConfigurationRevision</code> values.</p> <p>The resource is designed to configure multiple features (currently one feature, tracing). This type contains optional members that describe the configuration of these features (currently one member, <code>TraceConfiguration</code>). If a feature member isn't specified, the feature isn't enabled.</p>
    ObservabilityConfigurationStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    DeleteObservabilityConfigurationResponse:
      type: object
      required:
      - ObservabilityConfiguration
      properties:
        ObservabilityConfiguration:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfiguration'
          - description: A description of the App Runner observability configuration that this request just deleted.
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
