# x-archived-from: amazon-app-runner-x-amz-target-apprunner-listobservabilityconfigurations-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2020-05-15'
  x-release: v4
  title: 'AWS App Runner #X Amz Target=AppRunner.ListObservabilityConf…'
  description: 'App Runner

    App Runner is an application service that provides a fast, simple, and cost-effective way to go directly from an existing container image or source code to a running service in the Amazon Web Services Cloud in seconds.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apprunner
  x-aws-signingName: apprunner
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apprunner-2020-05-15.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: https://apprunner.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS App Runner multi-region endpoint
- url: http://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
- url: https://apprunner.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS App Runner endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AppRunner.ListObservabilityConfigurations'
paths:
  /#X-Amz-Target=AppRunner.ListObservabilityConfigurations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListObservabilityConfigurations
      description: 'Returns a list of active App Runner observability configurations in your Amazon Web Services account. You can query the revisions for a specific configuration name or the revisions for all active configurations in your account. You can optionally query only the latest revision of each requested name.


        To retrieve a full description of a particular configuration revision, call and provide one of the ARNs returned by ListObservabilityConfigurations.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListObservabilityConfigurationsResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListObservabilityConfigurationsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AppRunner.ListObservabilityConfigurations
      tags:
      - '#X Amz Target=AppRunner.ListObservabilityConfigurations'
      summary: List observability configurations
      x-summary-source: derived
components:
  schemas:
    AppRunnerResourceArn:
      type: string
      pattern: arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}
      minLength: 1
      maxLength: 1011
    Boolean:
      type: boolean
    NextToken:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    ObservabilityConfigurationName:
      type: string
      pattern: '[A-Za-z0-9][A-Za-z0-9\-_]{3,31}'
      minLength: 4
      maxLength: 32
    ObservabilityConfigurationSummary:
      type: object
      properties:
        ObservabilityConfigurationArn:
          allOf:
          - $ref: '#/components/schemas/AppRunnerResourceArn'
          - description: The Amazon Resource Name (ARN) of this observability configuration.
        ObservabilityConfigurationName:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfigurationName'
          - description: The customer-provided observability configuration name. It can be used in multiple revisions of a configuration.
        ObservabilityConfigurationRevision:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: 'The revision of this observability configuration. It''s unique among all the active configurations (<code>"Status": "ACTIVE"</code>) that share the same <code>ObservabilityConfigurationName</code>.'
      description: <p>Provides summary information about an App Runner observability configuration resource.</p> <p>This type contains limited information about an observability configuration. It includes only identification information, without configuration details. It's returned by the <a>ListObservabilityConfigurations</a> action. Complete configuration information is returned by the <a>CreateObservabilityConfiguration</a>, <a>DescribeObservabilityConfiguration</a>, and <a>DeleteObservabilityConfiguration</a> actions using the <a>ObservabilityConfiguration</a> type.</p>
    ListObservabilityConfigurationsResponse:
      type: object
      required:
      - ObservabilityConfigurationSummaryList
      properties:
        ObservabilityConfigurationSummaryList:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfigurationSummaryList'
          - description: A list of summary information records for observability configurations. In a paginated request, the request returns up to <code>MaxResults</code> records for each call.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token that you can pass in a subsequent request to get the next result page. It's returned in a paginated request.
    Integer:
      type: integer
    ListObservabilityConfigurationsRequest:
      type: object
      title: ListObservabilityConfigurationsRequest
      properties:
        ObservabilityConfigurationName:
          allOf:
          - $ref: '#/components/schemas/ObservabilityConfigurationName'
          - description: The name of the App Runner observability configuration that you want to list. If specified, App Runner lists revisions that share this name. If not specified, App Runner returns revisions of all active configurations.
        LatestOnly:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: '<p>Set to <code>true</code> to list only the latest revision for each requested configuration name.</p> <p>Set to <code>false</code> to list all revisions for each requested configuration name.</p> <p>Default: <code>true</code> </p>'
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResults'
          - description: <p>The maximum number of results to include in each response (result page). It's used for a paginated request.</p> <p>If you don't specify <code>MaxResults</code>, the request retrieves all available results in a single response.</p>
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: <p>A token from a previous result page. It's used for a paginated request. The request retrieves the next result page. All other parameter values must be identical to the ones that are specified in the initial request.</p> <p>If you don't specify <code>NextToken</code>, the request retrieves the first result page.</p>
    InternalServiceErrorException: {}
    InvalidRequestException: {}
    ObservabilityConfigurationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ObservabilityConfigurationSummary'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apprunner/
x-hasEquivalentPaths: true
